from app.models.usuarios import Usuarios
from app.models.aprendices import Aprendices
from app.models.administradores import Administrador
from app.models.instructores import Instructores
from app.models.operarios import Operarios
from app.models.animales import Animales
from app.models.animalesMejorados import AnimalesMejorados
from app.models.mejoramientosGeneticos import MejoramientosGeneticos
from app.models.controles import Controles
from app.models.vacunas import Vacunas
from app.models.aplicacionVacunas import AplicacionVacunas
